# Generated by Django 5.1.1 on 2024-10-09 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extradition',
            fields=[
                ('extradition_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_extradition', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('date_of_shipment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('product_type', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('extradition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.extradition')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsCurrentQuantity',
            fields=[
                ('product_current_quantity_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_quantity', to='warehouse.product')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='warehouse.user'),
        ),
        migrations.AddField(
            model_name='extradition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraditions', to='warehouse.user'),
        ),
        migrations.CreateModel(
            name='WriteOffOfProducts',
            fields=[
                ('id_product_write_off', models.AutoField(primary_key=True, serialize=False)),
                ('product_write_off_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='warehouse.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='write_off_of_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.writeoffofproducts'),
        ),
    ]
